name: Docker Image CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: |
          ls
          
          sudo ./gradlew build

      - name: Build the Docker image
        run: |
          docker version
          # 登录阿里云镜像仓库
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
          ls
          cd property-hive
          # 使用Dockerfile构建镜像
          docker build -t property_hive .
          # 推送镜像到镜像仓库
          docker push registry.cn-hangzhou.aliyuncs.com/Yoooum/property_hive
